FROM node:14-alpine

ENV DOMAIN http://renteree.com
ENV PORT 8080

ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG DATABASE_NAME
ARG DATABASE_URI
ARG STORAGE_BUCKET_NAME
ARG GOOGLE_CONSOLE_PROJECT_ID
ARG STORAGE_BUCKET_PRIVATE_KEY
ARG STORAGE_BUCKET_CLIENT_EMAIL

WORKDIR /build
COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build

EXPOSE 8080

# Direct usage of node instead npm for raising performance
CMD ["node", "dist/index.js"]
