version: 2.1

orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.2.0

jobs:
  lint_test_build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install packages
                command: npm ci
            - run:
                name: Run Lint
                command: npm run lint
            - run:
                name: Run Tests
                command: npm test
            - run:
                name: Run Build
                command: npm run build

  docker_build_push_deploy:
    executor: heroku/default
    steps:
      - heroku/install
      - heroku/check-authentication
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push a docker image
          description: Replacement of orb command heroku/push-docker-image because of its syntax error
          command: |
            heroku container:login
            heroku container:push -a $HEROKU_APP_NAME web
      - heroku/release-docker-image:
          app-name: $HEROKU_APP_NAME
          process-types: web

workflows:
  build:
    jobs:
      - lint_test_build
      - deployment_approval:
          type: approval
          requires:
            - lint_test_build
          filters:
            branches:
              only:
                - master
      - docker_build_push_deploy:
          context: renteree
          requires:
            - deployment_approval
